### ISSUE TITLE
Promise based

### ISSUE THREAD

**Issue by ssipos90** [thenativeweb/node-eventstore#111]
Hello,

In order to avoid callback hell, the library could use promises. I've tried wrapping stuff in promises but there are context issues (`this` is undefined)

eg 1:
```js
es.getEventStream({ aggregateId: 'someId' })
  .then(stream => { /* do some commits*/ })
  .catch(error => console.error(error));
```

eg 2:
```js
es.getNewId()
    .then(id => es.getEventStream({ aggregateId: id }))
    .then(stream => { /* do some commits*/ })
    .catch(error => console.error(error));
```

**Comment by adrai** [comment]
For these cqrs modules I don't want to support Promises... at least not in this major version 😉
I would design the whole thing a bit differently...

**Comment by ssipos90** [comment]
Hmmm... maybe I could invest a bit more time on this and do a PR implementing something in the lines of:
```js
import ES from '...';
import {promisify} from '...';

const es = promisify(new ES({...}));
// and use it promise based
```

**Comment by blissi** [comment]
@ssipos90 Would be greatly appreciated :-)!

**Comment by ssipos90** [comment]
@blissi I'll give it a shot around December 17th, I have some spare time then and I need this too.

**Comment by ssipos90** [comment]
@adrai , any plans for a promise version?

**Comment by adrai** [comment]
no time right now... but feel free to contribute...
I suggest an interface for both worlds promise-based and callback-based

**Comment by Glockenbeat** [comment]
We are using this along with bluebird, works great so far.

**Comment by ssipos90** [comment]
I've given it a shot, but `this` messes things up and I gave up.

**Comment by wi-ski** [comment]
Whats the status on this? :)

**Comment by ssipos90** [comment]
@wi-ski use bluebird promises to wrap this lib.

**Comment by justintime4tea** [comment]
"This" is probably undefined because when using import/export JavaScript is executed in a strict context unless your using Babel to transpile and then import/export should be transpile to require so then I don't know why it's be undefined. If your using "true" import/export to give proper context to "this" you would need to use one of bind, call, or apply. Not sure if any of this helps but good luck either way!

**Comment by justintime4tea** [comment]
Also instead of wrapping in promises you could try await/async :) not sure if that helps either lol I've become quite interested in event sourcing and event store so will be checking out this library more. If I end up using it I'll submit some PRs or try to repro and squash some bugs if I can find time.

**Comment by susannaroden** [comment]
Hey everyone 👋 

New maintainer here… we, i.e. @thenativeweb, have taken over the responsibility to maintain this module from @adrai, and I would like to give a little update on this issue:

We agree that supporting promises would be a major benefit for this module, so one of the first things we are going to do is to introduce a promise-based API. This will take some time, but for now I am closing this issue.

If you have any questions or anything else, please feel free to re-open it, or to open a new one 😊

**Comment by blissi** [comment]
Hi Susanna,
OT: greets from Rheinhausen to you and Golo ;-)
Nice that you will maintain this project!
