### ISSUE TITLE
[Question] Audit/Explorateur like LOKAD

### ISSUE THREAD

**Issue by AlexandreRoba** [thenativeweb/node-eventstore#77]
Hello, i was wondering if any of you built a nodejs web app that can be plugged on the eventstore that would allow for auditing and investigation? Something like the lokad ["maintain app"](http://lokad.github.io/lokad-cqrs/) . If not, I believe I would start one as I found it kind of handy.
thanks,
Alex.

**Comment by adrai** [comment]
No there is no web app right now...
in production we have the proprietary db tooling (i.e. for mongo, redis, etc...)
Feel free to start such a project... but try to implement it db agnostic...

**Comment by AlexandreRoba** [comment]
Yep. My intention was to use the eventstore api. Then I can leverage the multi db support.

**Comment by susannaroden** [comment]
Hey everyone 👋 

New maintainer here… we, i.e. @thenativeweb, have taken over the responsibility to maintain this module from @adrai, and I would like to give a little update on this issue:

It would be awesome to have such a maintenance UI for the event store, however we assume since nothing has happened in this issue for 4 years now, the project did not come alive, did it? For now, it probably doesn't make too much sense to start building something like that *now*, as we are going to update the API soon. Hence I am going to close this for now.

If you have any questions or anything else, please feel free to re-open it, or to open a new one 😊
